# nixpack.toml
version = "1.0"

[build]
packager = "pip"  # Specify pip as the packager

[dependencies]
python = "3.9.0"
mysqlclient = "*"

[build.dependencies]
# Include system libraries for MySQL
apt = ["default-libmysqlclient-dev", "build-essential"]
