[phases.setup]
nixPkgs = [
    "python39",
    "gcc",
    "libmysqlclient",
    "pkg-config"
]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn your_project.wsgi:application"