version = "1.0"

[build]
packager = "pip"

[dependencies]
python = "3.9.0"
mysqlclient = "*"

[build.dependencies]
# Install MySQL/MariaDB development libraries
apt = ["default-libmysqlclient-dev", "build-essential", "libssl-dev", "libffi-dev", "libmariadb-dev"]

# You may need additional packages depending on your environment.
