[phases.setup]
aptPkgs = ["default-libmysqlclient-dev", "pkg-config", "glibc-source", "libc6"]

[variables]
LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu"
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu"
MYSQLCLIENT_CFLAGS = "-I/usr/include/mysql"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/x86_64-linux-gnu -lmysqlclient"
