[phases.setup]
commands = [
  "sudo apt-get update",
  "sudo apt-get install -y wget default-libmysqlclient-dev pkg-config build-essential",
  "wget http://ftp.gnu.org/gnu/libc/glibc-2.36.tar.gz",
  "tar -xvzf glibc-2.36.tar.gz",
  "cd glibc-2.36 && mkdir build && cd build && ../configure --prefix=/usr && make && sudo make install"
]

aptPkgs = ["wget", "default-libmysqlclient-dev", "pkg-config", "build-essential", "glibc-source", "libc6"]

[variables]
LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu"
LD_LIBRARY_PATH = "/usr/lib/x86_64-linux-gnu"
MYSQLCLIENT_CFLAGS = "-I/usr/include/mysql"
MYSQLCLIENT_LDFLAGS = "-L/usr/lib/x86_64-linux-gnu -lmysqlclient"
