version = "1.0"

[build]
packager = "pip"  # Specify pip as the packager

[dependencies]
python = "3.9.0"

# Include system libraries for MySQL under dependencies, not build
apt = ["default-libmysqlclient-dev", "build-essential", "pkg-config", "python3-dev"]
